
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        id: test
        run: 
          docker compose run --rm app sh -c "python manage.py test"
         # echo "testStatus=$?" >> $GITHUB_STATE #save test status to state
        continue-on-error: true
        outputs:
          testStatus: $?

      - name: Lint Code
        id: lint
        run: |
          docker compose run --rm app sh -c "flake8"
         # echo "lintStatus=$?" >> $GITHUB_STATE  # Save lint status to state
        continue-on-error: true
        outputs:
          lintStatus: $?

      # Accessing and using outputs
      - name: Report Results
        run: |
          echo "Test Status: ${{ steps.test.outputs.testStatus }}"
          echo "Lint Status: ${{ steps.lint.outputs.lintStatus }}"
